### ISSUE TITLE
Does Graph-Tool implement Mixed-Membership Stochastic Block Models? 

### ISSUE THREAD

**Issue by alexlenail** [antmd/graph-tool#1]
Hello graph-tool developers, (@count0)

I see that you've implemented Stochastic Block Models and a couple variants in this library. I was wondering whether [Mixed Membership SBM](http://jmlr.csail.mit.edu/papers/volume9/airoldi08a/airoldi08a.pdf) was implemented here (are those the same as overlapping SBM?)

I'm also curious about how you perform inference. Do you use an outside engine (e.g. PyMC3) or are you implementing all of this yourselves, or something else?

**Comment by count0** [comment]
This is not the main graph-tool repository; it is just some random fork. The main repository is here: https://git.skewed.de/count0/graph-tool

Also, issues should not be used to ask questions. They should be used to report problems.

To answer your questions: Yes, the overlapping SBM is a particular kind of mixed membership SBM. Inference is performed using MCMC, implemented in C++. No outside "engine" is used.

**Comment by alexlenail** [comment]
Sorry @count0!
